### ISSUE TITLE
Could pl. list of all extenstions and purpose of each 

### ISSUE THREAD

**Issue by nagkumar** [RVRhub/datafaker-gen-extension#1]
>This is a collection of extensions for the

it just says they are collection but does not give names of each extension and it's oneliner use.. pl. see if you could improve the readme.md to capture this info too.

hope this is the list of providers that already exist in the main faker

https://www.datafaker.net/documentation/providers/

**Comment by RVRhub** [comment]
Yes, at the moment only one RabbitMq Sink has been added. I plan to add new extensions in the future.
Currently the core Datafake Gen already has:
- Formats: SQL/JSON/CSV/XML/YAML.
- Sinks: Comman line/Text file.

If you have any ideas for other extensions, we can create an issue for this and implement it.
